#!/usr/bin/env bash

# Unlock vaults
echo "Opening vault-a on ${1}3..."
sudo cryptsetup open ${1}3 vault-a
echo "Opening vault-b on ${1}4..."
sudo cryptsetup open ${1}4 vault-b
echo "Opening vault-c on ${1}5..."
sudo cryptsetup open ${1}5 vault-c

# Mount vaults to directories
echo "Creating mount directories..."
sudo mkdir /mnt/vault-a /mnt/vault-b /mnt/vault-c
echo "Mounting vault-a, vault-b, and vault-c..."
sudo mount /dev/mapper/vault-a /mnt/vault-a
sudo mount /dev/mapper/vault-b /mnt/vault-b
sudo mount /dev/mapper/vault-c /mnt/vault-c
