#!/usr/bin/env bash

# Unmount vaults
echo "Unmounting vault directories..."
sudo umount /mnt/vault-a
sudo umount /mnt/vault-b
sudo umount /mnt/vault-c

# Close vaults
echo "Closing vault-a, vault-b, and vault-c..."
sudo cryptsetup close vault-a
sudo cryptsetup close vault-b
sudo cryptsetup close vault-c

# Unmount home volume
echo "Unmounting live partition..."
udisksctl unmount -b ${1}4
