#!/usr/bin/env bash

# Determine the root
if [ -z "$1" ]; then
    u_root=$(./ursa--detect)
else
    u_root=$1
fi

# Unmount, detach, clean up
echo "Removing ${u_root}..."
./ursa--unmount ${u_root}
./ursa--detach ${u_root}
./ursa--cleanup
