#!/usr/bin/env bash

u_root=$(./ursa--detect)

# Mount
./ursa--mount ${u_root}

# Open all vaults with default file managers
echo "Opening vault directories..."
open /mnt/vault-a /mnt/vault-b /mnt/vault-b /mnt/vault-c
