#!/usr/bin/env bash

# Get latest ursa in /tmp
echo "Cloning repo from GitHub..."
git clone https://github.com/myTerminal/ursa /tmp/ursa

# Determine current command location
if [ $(command -v realpath) ]; then
    root_directory=$(readlink -f "${BASH_SOURCE[0]}" | xargs realpath | xargs dirname)
else
    root_directory=$(cd "$(dirname $BASH_SOURCE[0])" ; pwd -P)
fi
echo "Detected ursa at ${root_directory}!"

# Deploy commands to determined location
echo "Deploying commands..."
cp /tmp/ursa/ursa-* $root_directory

# Clean /tmp
echo "Cleaning up..."
rm -rf /tmp/ursa

echo "Update complete!"
